
// Code generated by gox; DO NOT EDIT.
package gox
import (
	"github.com/caleb-sideras/goxstack/src/pages/docs/render"
	"github.com/caleb-sideras/goxstack/src/pages/examples/data/rn"
	"github.com/caleb-sideras/goxstack/src/pages/examples/render"
	"github.com/caleb-sideras/goxstack/src/pages/docs/index"
	"github.com/caleb-sideras/goxstack/src/pages/examples/data"
	"github.com/caleb-sideras/goxstack/src/pages/home_"
	"github.com/caleb-sideras/goxstack/src/pages/examples/pages"
	"github.com/caleb-sideras/goxstack/src/pages/docs/router"
	"github.com/caleb-sideras/goxstack/src/pages/docs/introduction_"
	"github.com/caleb-sideras/goxstack/src/pages/docs/pages"
	"github.com/caleb-sideras/goxstack/src/pages/docs/routing"
	"github.com/caleb-sideras/goxstack/src/pages/nav"
	"github.com/caleb-sideras/goxstack/src/pages/docs/data"
	"github.com/caleb-sideras/goxstack/src/pages/docs/handle"
	"github.com/caleb-sideras/goxstack/src/pages/examples/todo"
)

var IndexList = map[string]string{
	"/docs/handle" : "pages/docs/index.html",
	"/docs" : "pages/docs/index.html",
	"/docs/router" : "pages/docs/index.html",
	"/tmp" : "pages/index.html",
	"/examples" : "pages/examples/index.html",
	"/examples/data" : "pages/examples/index.html",
	"/examples/data/rn" : "pages/examples/data/rn/index.html",
	"/docs/pages" : "pages/docs/index.html",
	"/examples/pages" : "pages/examples/index.html",
	"/examples/render" : "pages/examples/index.html",
	"/nav" : "pages/index.html",
	"/docs/data" : "pages/docs/index.html",
	"/" : "pages/index.html",
	"/docs/render" : "pages/docs/index.html",
	"/docs/routing" : "pages/docs/index.html",
	"/examples/pages/examples" : "pages/examples/pages/examples/index.html",
	"/docs/index" : "pages/docs/index.html",
	"/examples/todo" : "pages/examples/index.html",
}

var PagesList = map[string]PageData{
	"/examples/pages": {Data:example_pages.Data, Index: "pages/examples/index.html", Page: "pages/examples/pages/page.html"},
	"/examples/pages/examples": {Data: EmptyPageData, Index: "pages/examples/pages/examples/index.html", Page: "pages/examples/pages/examples/page.html"},
	"/examples/render": {Data:example_render.Data, Index: "pages/examples/index.html", Page: "pages/examples/render/page.html"},
	"/examples/data": {Data:example_data.Data, Index: "pages/examples/index.html", Page: "pages/examples/data/page.html"},
	"/examples/todo": {Data:todo.Data, Index: "pages/examples/index.html", Page: "pages/examples/todo/page.html"},
	"/docs": {Data:introduction.Data, Index: "pages/docs/index.html", Page: "pages/docs/introduction_/page.html"},
	"/tmp": {Data: EmptyPageData, Index: "pages/index.html", Page: "pages/tmp/page.html"},
}

var DataList = map[string]DataRender{
	"/": {Data:home.Data, Index: "pages/index.html", Page: "pages/home_/page.html"},
	"/examples/data/rn": {Data:rn.Data, Index: "pages/examples/data/rn/index.html", Page: "pages/examples/data/rn/page.html"},
}

var RenderList = []RenderDefault{
	{"/docs/render", render.Render},
	{"/docs/routing", routing.Render},
	{"/examples/pages/code", example_pages.Code_},
	{"/examples/pages/example", example_pages.Example_},
	{"/examples/render/markdown", example_render.Markdown_},
	{"/examples/render/code", example_render.Code_},
	{"/docs/index", index.Render},
	{"/docs/data", data.Render},
	{"/docs/handle", handle.Render},
	{"/examples/data/code", example_data.Code_},
	{"/docs/router", router.Render},
	{"/examples/todo/code", todo.Code_},
	{"/examples/todo/ssr", todo.Ssr_},
	{"/docs/pages", pages.Render},
}

var HandleList = []HandlerDefault{
	{"/nav/home", nav.Home_},
	{"/nav/examples", nav.Examples_},
	{"/nav/docs", nav.Docs_},
	{"/examples/todo/handleaddtask", todo.HandleAddTask_},
}
