
// Code generated by gox; DO NOT EDIT.
package gox
import (
	"github.com/caleb-sideras/gox-starter/src/pages/home_"
)

var IndexList = map[string]string{
	"/" : "pages/index.html",
}

var PagesList = map[string]PageData{
	"/": {Data:home.Data, Index: "pages/index.html", Page: "pages/home_/page.html"},
}

var DataList = map[string]DataRender{
	
}

var RenderList = []RenderDefault{
	
}

var HandleList = []HandlerDefault{
	
}
