
// Code generated by gox; DO NOT EDIT.
package gox
import (
	"github.com/caleb-sideras/goxstack/src/pages/home_"
	"github.com/caleb-sideras/goxstack/src/pages/docs/introduction_"
	"github.com/caleb-sideras/goxstack/src/pages/docs/pages"
	"github.com/caleb-sideras/goxstack/src/pages/example"
	"github.com/caleb-sideras/goxstack/src/pages/docs/handle"
	"github.com/caleb-sideras/goxstack/src/pages/docs/render"
	"github.com/caleb-sideras/goxstack/src/pages/docs/router"
	"github.com/caleb-sideras/goxstack/src/pages/docs/routing"
	"github.com/caleb-sideras/goxstack/src/pages/docs/data"
	"github.com/caleb-sideras/goxstack/src/pages/docs/index"
)

var IndexList = map[string]string{
	"/docs/pages" : "pages/docs/index.html",
	"/example" : "pages/index.html",
	"/docs/index" : "pages/docs/index.html",
	"/docs/router" : "pages/docs/index.html",
	"/docs/routing" : "pages/docs/index.html",
	"/docs" : "pages/docs/index.html",
	"/tmp" : "pages/index.html",
	"/docs/data" : "pages/docs/index.html",
	"/docs/handle" : "pages/docs/index.html",
	"/docs/render" : "pages/docs/index.html",
	"/" : "pages/index.html",
}

var PagesList = map[string]PageData{
	"/docs": {Data:introduction.Data, AdditionalTemplates: []string{"pages/docs/index.html", "pages/docs/introduction_/page.html",},},
	"/example": {Data:example.Data, AdditionalTemplates: []string{"pages/index.html", "pages/example/page.html",},},
	"/tmp": {Data: EmptyPageData,  AdditionalTemplates: []string{"pages/index.html", "pages/tmp/page.html",},},
}

var DataList = map[string]DataRender{
	"/": {Data:home.Data, AdditionalTemplates: []string{"pages/index.html", "pages/home_/page.html",},},
}

var RenderList = []RenderDefault{
	{"/docs/render", render.Render},
	{"/docs/router", router.Render},
	{"/docs/routing", routing.Render},
	{"/docs/pages", pages.Render},
	{"/example/todocsr", example.TodoCsr_},
	{"/example/todossr", example.TodoSsr_},
	{"/docs/data", data.Render},
	{"/docs/handle", handle.Render},
	{"/docs/index", index.Render},
}

var HandleList = []HandlerDefault{
	{"example/handleaddtask", example.HandleAddTask_},
}
