// Code generated by gox; DO NOT EDIT.
package gox

import (
	"calebsideras.com/gox/src/pages/docs"
	"calebsideras.com/gox/src/pages/example"
	home "calebsideras.com/gox/src/pages/home_"
)

			var RenderRouteList = map[string]GeneratedPageData{
				"/example": {PageData:example.Data, GeneratedTemplates: []string{"pages/index.html", "pages/example/page.html",},},
	"": {PageData:home.Data, GeneratedTemplates: []string{"pages/index.html", "pages/home_/page.html",},},
			}

			var RenderCustomList = []RenderCustom{
				{docs.PreRenderDocs_},
			}

			var RenderDefaultList = []RenderDefault{
				{"/example/todocsr", example.TodoCsr},
	{"/example/todossr", example.TodoSsr},
			}

			var HandlerDefaultList = []HandlerDefault{
				{"/example/handleaddtask", example.HandleAddTask},
			}
			